USE dreamnestai;

INSERT INTO products
  (name, brand, category, room_type, style, price_inr, product_url, image_url, description, tags, source, is_active)
VALUES
  (
    'GLOSTAD 3-seat sofa',
    'IKEA',
    'sofa',
    'living_room',
    'modern',
    NULL,
    'https://www.ikea.com/in/en/p/glostad-3-seat-sofa-knisa-dark-gray-20489010/',
    'https://www.ikea.com/in/en/images/products/glostad-3-seat-sofa-knisa-dark-gray__0950868_pe800338_s5.jpg?f=xs',
    'Compact three-seater with clean, modern lines.',
    JSON_ARRAY('modern', 'compact', 'gray'),
    'ikea',
    1
  ),
  (
    'SÖDERHAMN 3-seat sofa with chaise',
    'IKEA',
    'sofa',
    'living_room',
    'modern',
    NULL,
    'https://www.ikea.com/in/en/p/soederhamn-3-seat-sofa-with-chaise-longue-tonerud-red-s59449507/',
    'https://www.ikea.com/in/en/images/products/soederhamn-3-seat-sofa-with-chaise-longue-tonerud-red__1041631_pe841330_s5.jpg?f=xs',
    'Deep seating and relaxed lounge feel.',
    JSON_ARRAY('modern', 'lounge', 'chaise'),
    'ikea',
    1
  ),
  (
    'LACK coffee table',
    'IKEA',
    'coffee_table',
    'living_room',
    'minimal',
    NULL,
    'https://www.ikea.com/in/en/p/lack-coffee-table-black-brown-00104291/',
    NULL,
    'Minimal, versatile coffee table.',
    JSON_ARRAY('minimal', 'budget', 'black'),
    'ikea',
    1
  ),
  (
    'RÅSKOG utility cart',
    'IKEA',
    'storage',
    'kitchen',
    'industrial',
    NULL,
    'https://www.ikea.com/in/en/p/raskog-utility-cart-black-40336022/',
    NULL,
    'Mobile cart for kitchen or workspace.',
    JSON_ARRAY('industrial', 'utility', 'storage'),
    'ikea',
    1
  ),
  (
    'MALM bed frame',
    'IKEA',
    'bed',
    'bedroom',
    'modern',
    NULL,
    'https://www.ikea.com/in/en/p/malm-bed-frame-high-black-brown-luroey-s09069764/',
    NULL,
    'Classic low-profile bed frame.',
    JSON_ARRAY('modern', 'bedroom'),
    'ikea',
    1
  ),
  (
    'MICKE desk',
    'IKEA',
    'desk',
    'office',
    'minimal',
    NULL,
    'https://www.ikea.com/in/en/p/micke-desk-white-90214308/',
    NULL,
    'Compact study/work desk.',
    JSON_ARRAY('minimal', 'study'),
    'ikea',
    1
  ),
  (
    'Country Console Table',
    'Pepperfry',
    'console_table',
    'living_room',
    'classic',
    NULL,
    'https://www.pepperfry.com/country-console-table-in-walnut-colour-by-amberville-1945870.html',
    NULL,
    'Warm walnut console table.',
    JSON_ARRAY('classic', 'walnut'),
    'pepperfry',
    1
  ),
  (
    'Jove 1 Seater Sofa',
    'Pepperfry',
    'armchair',
    'living_room',
    'modern',
    NULL,
    'https://www.pepperfry.com/jove-1-seater-sofa-in-beige-colour-by-trevi-furniture-1878963.html',
    NULL,
    'Soft beige accent chair.',
    JSON_ARRAY('modern', 'beige', 'accent'),
    'pepperfry',
    1
  ),
  (
    'Wakesure 3 Seater Sofa',
    'Flipkart',
    'sofa',
    'living_room',
    'modern',
    NULL,
    'https://www.flipkart.com/wakesure-premium-quality-jute-fabric-3-seater-sofa/p/itmfdb01ede7b5b9?pid=SOFGZHE4NHTMCPU9&lid=LSTSOFGZHE4NHTMCPU9GJYBRC&marketplace=FLIPKART&cmpid=content_sofa_8965229628_gmc',
    NULL,
    'Premium quality jute fabric 3-seater sofa.',
    JSON_ARRAY('modern', 'jute', '3-seater'),
    'flipkart',
    1
  );
